# This is a joke teller program.
print ('What do you get when you cross a snowman with a vampire?')
input ()
print ('Frostbite!')
input ()
print ()
print ('Do you know hemorrhoids are hereditary?')
input ()
print ('Because they run in your Jeans\\genes')
input ()
print ()
print ("What o dentists call an astronaut's cavity?")
input ()
print ('A black hole')
input ()
print ()
print ('Knock knock.')
input ()
print ('Whos\'s there?')
input ()
print ('Intrrupting cow.')
input ()
print ('Interrupting caow Wh', end='')
print ('-MOO!')
